### ISSUE TITLE
Ordering of CSS rules

### ISSUE THREAD

**Issue by chrisdavies** [mhallin/forest#11]
CSS is order-aware, and overriding CSS rules is a commonly done thing.

For example:

```clj
[.foo {:border "5px solid transparent"
          :border-top-color "inherit"}]
```

I'd expect this to generate the following CSS:

```css
.foo {
  border: 5px solid transparent;
  border-top-color: inherit;
}
```

Instead, it ignores order (because maps in Clojure are unordered), and in my case is producing this:

```css
.foo {
  border-top-color: inherit;
  border: 5px solid transparent;
}
```

Which is wrong, as no top-border will be displayed.

So, my question is: is there a way to ensure the CSS property order? Maybe using a vector:

```cljs
[.foo [:border "5px solid transparent"
          :border-top-color "inherit"]]
```
